#!/bin/bash
#SBATCH --job-name=ldsc_h2
#SBATCH --error=%x-%j.error
#SBATCH --out=%x-%j.out
#SBATCH --mem=40G
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=7-0:0:0
#conda activate ldsc
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM1.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM1.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM2.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM2.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM3.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM3.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM4.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM4.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM5.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM5.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM6.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM6.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM7.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM7.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM8.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM8.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM9.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM9.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM10.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM10.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM11.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM11.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM12.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM12.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM13.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM13.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM14.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM14.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM15.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM15.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM16.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM16.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM17.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM17.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM18.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM18.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM19.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM19.ldsc.res.txt
python /data/sbcs/GuoLab/backup/liq17/biosoft/ldsc/ldsc.py --h2 /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM20.glm.logistic.ldsc.txt --ref-ld-chr /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /data/sbcs/GuoLab/backup/liq17/ref/Alkesgroup/eur_w_ld_chr/ --out /data/sbcs/GuoLab/backup/liq17/CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM20.ldsc.res.txt
