#!/bin/bash
#SBATCH --job-name=ldsc_h2
#SBATCH --error=%x-%j.error
#SBATCH --out=%x-%j.out
#SBATCH --mem=40G
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=7-0:0:0
#conda activate ldsc
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM1.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM1.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM2.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM2.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM3.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM3.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM4.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM4.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM5.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM5.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM6.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM6.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM7.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM7.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM8.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM8.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM9.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM9.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM10.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM10.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM11.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM11.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM12.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM12.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM13.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM13.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM14.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM14.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM15.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM15.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM16.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM16.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM17.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM17.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM18.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM18.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM19.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM19.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM20.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM20.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM21.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM21.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM22.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM22.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM23.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM23.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM24.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM24.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM25.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM25.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM26.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM26.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM27.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM27.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM28.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM28.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM29.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM29.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM30.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM30.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM31.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM31.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM32.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM32.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM33.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM33.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM34.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM34.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM35.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM35.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM36.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM36.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM37.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM37.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM38.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM38.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM39.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM39.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM40.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM40.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM41.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM41.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM42.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM42.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM43.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM43.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM44.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM44.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM45.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM45.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM46.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM46.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM47.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM47.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM48.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM48.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM49.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM49.ldsc.res.txt
python /biosoft/ldsc/ldsc.py --h2 /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//simulation_values_res/sim_y_values/beta1_1_h2_0.5_SNPs_1000.sim_y/10M.SIM50.glm.logistic.ldsc.txt --ref-ld-chr /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision//84Tracks/ldscores_sim1000/ --w-ld-chr /ref/Alkesgroup/eur_w_ld_chr/ --out /CRC_TF_TWAS_zhishan2024/NC_revision_OceanCode/v2_NC_revision/simulation_values_res/ldsc_res/beta1_1_h2_0.5_SNPs_1000/SIM50.ldsc.res.txt
